before_install:
  - git clone https://github.com/jbussdieker/libsass.git
  - git clone https://github.com/hcatlin/sass-spec.git
install:
  - cd libsass
  - autoreconf -i
  - ./configure
  - sudo make install
  - cd ..
script:
  - autoreconf -i
  - ./configure
  - sudo make install
after_script:
  - cd sass-spec
  - ./sass-spec.rb -c sassc -s --ignore-todo
