before_install:
  - git clone https://github.com/jbussdieker/libsass.git
install:
  - cd libsass
  - autoreconf -i
  - ./configure
  - make
  - sudo make install
script:
  - autoreconf -i
  - ./configure
  - make
  - sudo make install
